# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rdhpf < Formula
  desc "Automatically forward published container ports from a remote Docker host to localhost via SSH"
  homepage "https://github.com/tomaszpeksa/remote-docker-host-port-forwarder"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomaszpeksa/remote-docker-host-port-forwarder/releases/download/v0.1.9/remote-docker-host-port-forwarder_0.1.9_Darwin_x86_64.tar.gz"
      sha256 "539dcd10bdd2f4bbc46736570a0d709b1a7ef8b4e6ac737c5fca67dd5b532b33"

      def install
        bin.install "rdhpf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomaszpeksa/remote-docker-host-port-forwarder/releases/download/v0.1.9/remote-docker-host-port-forwarder_0.1.9_Darwin_arm64.tar.gz"
      sha256 "5f4289a223cb55f794c2d76d245d093d8cb5440f335db6df5d1543ff9f28c031"

      def install
        bin.install "rdhpf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomaszpeksa/remote-docker-host-port-forwarder/releases/download/v0.1.9/remote-docker-host-port-forwarder_0.1.9_Linux_x86_64.tar.gz"
      sha256 "501b87907ab1683db9e487fbd20f69fb5c59b64fdfcafe0cccab3b071675afaa"
      def install
        bin.install "rdhpf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomaszpeksa/remote-docker-host-port-forwarder/releases/download/v0.1.9/remote-docker-host-port-forwarder_0.1.9_Linux_arm64.tar.gz"
      sha256 "55feb78bb7d86d96f500752853562aefa62678c493251bfaf81faabd5408bb24"
      def install
        bin.install "rdhpf"
      end
    end
  end

  test do
    system "#{bin}/rdhpf", "version"
  end
end
