# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RemoteDockerHostPortForwarder < Formula
  desc "Automatically forward published container ports from a remote Docker host to localhost via SSH"
  homepage "https://github.com/tomaszpeksa/remote-docker-host-port-forwarder"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomaszpeksa/remote-docker-host-port-forwarder/releases/download/v0.1.1/remote-docker-host-port-forwarder_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "aae36b8880bc99aa9a6967f9361fd306fd11338dc155c5860709aa1594cff91d"

      def install
        bin.install "rdhpf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomaszpeksa/remote-docker-host-port-forwarder/releases/download/v0.1.1/remote-docker-host-port-forwarder_0.1.1_Darwin_arm64.tar.gz"
      sha256 "47e24a52625e70e28c91b48fea82f1eecab5d10dda9886207c7ebbddf2c02299"

      def install
        bin.install "rdhpf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomaszpeksa/remote-docker-host-port-forwarder/releases/download/v0.1.1/remote-docker-host-port-forwarder_0.1.1_Linux_x86_64.tar.gz"
      sha256 "cdf5c705c2e2a1f2da527160d2757abcff9e83a0fa68a33435b76edc41895f01"
      def install
        bin.install "rdhpf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomaszpeksa/remote-docker-host-port-forwarder/releases/download/v0.1.1/remote-docker-host-port-forwarder_0.1.1_Linux_arm64.tar.gz"
      sha256 "b27db5e3bd6822ca1926dffb638630e9d1b264f86d177b9d97d1211680f775a2"
      def install
        bin.install "rdhpf"
      end
    end
  end

  test do
    system "#{bin}/rdhpf", "version"
  end
end
